name = "zoom-ai-minuter"
main = "src/index.ts"
compatibility_date = "2023-09-04"

# ローカル開発時の環境変数読み込み設定
[vars]
APP_ENV = "development"

# KVストレージ名前空間の設定
[[kv_namespaces]]
binding = "JOB_KV"
id = "xxxxxxxx" # このIDはCloudflare KV作成時に取得する値
preview_id = "yyyyyyyy" # ローカル開発用のID

# 開発環境設定
[env.development]
workers_dev = true
# 開発環境では .env ファイルから環境変数を読み込む

# 本番環境設定
[env.production]
workers_dev = false
# 本番環境ではCloudflare Secretsを使用
# zone_id と routes は実際のドメイン設定に合わせて変更する
zone_id = "your_zone_id"
routes = ["example.com/api/*"]
